# Generated by Django 5.2.1 on 2025-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidaarancelaria',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='partidaarancelaria',
            name='referencia_legal',
        ),
        migrations.RemoveField(
            model_name='partidaarancelaria',
            name='subpartidas',
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='ace22_chi_prot',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='ace66_mexico',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='can_ace36_ace47_ven',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='capitulo',
            field=models.CharField(default='Sin datos', max_length=10),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='despacho_frontera',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='disp_legal',
            field=models.TextField(default='Sin datos'),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='entidad_emite',
            field=models.CharField(default='Sin datos', max_length=100),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='ice_iehd',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='partida',
            field=models.CharField(default='Sin datos', max_length=10),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='subpartida',
            field=models.CharField(default='Sin datos', max_length=10),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='tipo_documento',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='unidad_medida',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='codigo',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='descripcion',
            field=models.TextField(default='Sin datos'),
        ),
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='gravamen',
            field=models.CharField(default='Sin datos', max_length=50),
        ),
    ]
