# Generated by Django 5.2.1 on 2025-06-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_remove_partidaarancelaria_permisos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidaarancelaria',
            name='permisos',
            field=models.TextField(default='Sin datos'),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='referencia_legal',
            field=models.TextField(default='Sin datos'),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='subpartidas',
            field=models.TextField(default='Sin datos'),
        ),
    ]
