# Generated by Django 5.2.4 on 2025-10-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_partidaarancelaria_permisos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ranking de productos buscados',
                'verbose_name_plural': 'Ranking de productos buscados',
            },
        ),
    ]
