# Generated by Django 5.2.4 on 2025-10-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0004_searchstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStatisticDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cuenta diaria de búsquedas',
                'verbose_name_plural': 'Cuentas diarias de búsquedas',
                'unique_together': {('capitulo', 'fecha')},
            },
        ),
    ]
