# Generated by Django 5.2.4 on 2025-10-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0005_searchstatisticdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStatisticTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=100, unique=True)),
                ('total', models.BigIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ranking acumulado de búsquedas',
                'verbose_name_plural': 'Ranking acumulado de búsquedas',
            },
        ),
    ]
