# Generated by Django 5.2.4 on 2025-10-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0006_searchstatistictotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStatisticProductTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.BigIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ranking de productos buscados',
                'verbose_name_plural': 'Ranking de productos buscados',
            },
        ),
        migrations.AlterModelOptions(
            name='searchstatistictotal',
            options={'verbose_name': 'Ranking de capítulos buscados', 'verbose_name_plural': 'Ranking de capítulos buscados'},
        ),
    ]
