# Generated by Django 5.2.4 on 2025-10-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0008_exportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='resultados',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partidaarancelaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
