# Generated by Django 5.2.4 on 2025-11-05 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0010_clicklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('fecha_norma', models.DateField(blank=True, null=True)),
                ('numero_resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('nota', models.CharField(blank=True, max_length=250, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='referencias/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='partidas.partidaarancelaria')),
            ],
        ),
    ]
