# Generated by Django 5.2.4 on 2025-11-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0012_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatemporal',
            name='notified_pre_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
