# Generated by Django 5.2.4 on 2025-11-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0014_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
