# Generated by Django 5.2.4 on 2025-11-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0015_notificationlog_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='filtros',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
