# Generated by Django 5.2.4 on 2025-11-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0016_busqueda_filtros_busqueda_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busqueda',
            name='filtros',
        ),
        migrations.RemoveField(
            model_name='busqueda',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='busqueda',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='manual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
