# Generated by Django 5.2.4 on 2025-11-22 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0017_remove_busqueda_filtros_remove_busqueda_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=254)),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
