# Generated by ChatGPT - add 'nombre' field to SolicitudSoporte
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0018_solicitudsoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsoporte',
            name='nombre',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
    ]
