# Generated by Django 5.2.4 on 2025-12-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0019_solicitudsoporte_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='capitulo',
            field=models.CharField(default='Sin datos', max_length=200),
        ),
    ]
