# Generated by Django 5.2.4 on 2025-12-07 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0020_alter_partidaarancelaria_capitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('importadas', models.PositiveIntegerField(default=0)),
                ('omitidas', models.PositiveIntegerField(default=0)),
                ('errores', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
