# Generated by Django 5.2.4 on 2025-12-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0021_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='importadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='nombre_archivo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importlog',
            name='omitidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='total_filas',
            field=models.IntegerField(default=0),
        ),
    ]
